# GitHub Actions Secrets and Variables Configuration
# gTek Integrated Ecosystem - Iron Rule Framework Compliant
# Codex Sovereign ID: DIV-LA-JHILL-STFL02035

metadata:
  project: "gTek Integrated Ecosystem"
  owner: "Jerome Elston Hill Jr."
  entity: "Home Made Productions"
  iron_rule: "Commission or charitable donation only"
  rhodium_backed: true
  ancient_wisdom: "Saqqara-Giza protocols"

# Repository Secrets Configuration
secrets:
  # Docker Configuration
  docker:
    - name: "DOCKER_PAT"
      description: "Docker Hub Personal Access Token for gTek containers"
      required: true
      scope: "repository"
      iron_rule_compliant: true
    
    - name: "DOCKER_REGISTRY"
      description: "Custom Docker registry endpoint"
      required: false
      scope: "repository"
      default: "registry.hub.docker.com"

  # Deployment Secrets
  deployment:
    - name: "VERCEL_TOKEN"
      description: "Vercel deployment token for Saqqara Workflow"
      required: true
      scope: "repository"
      iron_rule_compliant: true
    
    - name: "VERCEL_ORG_ID"
      description: "Vercel organization ID for gTek"
      required: true
      scope: "repository"
    
    - name: "VERCEL_PROJECT_ID"
      description: "Vercel project ID for main deployment"
      required: true
      scope: "repository"

  # Ancient Wisdom & Iron Rule APIs
  iron_rule:
    - name: "RHODIUM_VERIFICATION_ENDPOINT"
      description: "Rhodium collateral verification API endpoint"
      required: true
      scope: "repository"
      ancient_wisdom: true
    
    - name: "IRON_RULE_COMPLIANCE_API"
      description: "Iron Rule Framework compliance API key"
      required: true
      scope: "repository"
      iron_rule_compliant: true
    
    - name: "ANCIENT_WISDOM_DB_URL"
      description: "Ancient wisdom database connection string"
      required: true
      scope: "repository"
      ancient_wisdom: true

  # AI & Samsung Integration
  ai_samsung:
    - name: "OPENAI_API_KEY"
      description: "OpenAI API key for PolyStack IDE AI features"
      required: true
      scope: "repository"
    
    - name: "SAMSUNG_DEV_KEY"
      description: "Samsung Developer API key for Knox integration"
      required: true
      scope: "repository"
      samsung_exclusive: true
    
    - name: "KNOX_API_KEY"
      description: "Samsung Knox API key for gDaTaNomOcS"
      required: true
      scope: "repository"
      samsung_exclusive: true

  # Database & Infrastructure
  infrastructure:
    - name: "POSTGRES_PASSWORD"
      description: "PostgreSQL password for ancient wisdom data"
      required: true
      scope: "repository"
    
    - name: "REDIS_PASSWORD"
      description: "Redis password for rhodium transaction cache"
      required: true
      scope: "repository"
    
    - name: "ENCRYPTION_KEY"
      description: "AES-256 encryption key for data sovereignty"
      required: true
      scope: "repository"
      generate: "random_256_bit"

  # Notification & Monitoring
  monitoring:
    - name: "SLACK_WEBHOOK_URL"
      description: "Slack webhook for deployment notifications"
      required: false
      scope: "repository"
    
    - name: "DATADOG_API_KEY"
      description: "Datadog API key for monitoring"
      required: false
      scope: "repository"

# Repository Variables Configuration
variables:
  # Project Metadata
  project:
    - name: "DOCKER_USER"
      value: "ceptokrem"
      description: "Docker Hub username for gTek containers"
      iron_rule_compliant: true
    
    - name: "PROJECT_NAME"
      value: "gtek-integrated-ecosystem"
      description: "Main project identifier"
    
    - name: "CODEX_SOVEREIGN_ID"
      value: "DIV-LA-JHILL-STFL02035"
      description: "Codex Sovereign Identity for Iron Rule Framework"
      iron_rule_compliant: true

  # Environment Configuration
  environment:
    - name: "NODE_VERSION"
      value: "18.x"
      description: "Node.js version for all applications"
    
    - name: "PYTHON_VERSION"
      value: "3.11"
      description: "Python version for LiquiNomOcs calculations"
    
    - name: "DOCKER_BUILDKIT"
      value: "1"
      description: "Enable Docker BuildKit for efficient builds"

  # Iron Rule Framework
  iron_rule_framework:
    - name: "IRON_RULE_FRAMEWORK"
      value: "Commission or charitable donation only"
      description: "Iron Rule Framework enforcement message"
      iron_rule_compliant: true
    
    - name: "RHODIUM_COLLATERAL_PERCENTAGE"
      value: "15"
      description: "Required rhodium collateralization percentage"
      ancient_wisdom: true
    
    - name: "COMMISSION_ONLY_MODE"
      value: "true"
      description: "Enforce commission-only engagement structure"
      iron_rule_compliant: true

  # Ancient Wisdom Configuration
  ancient_wisdom:
    - name: "SAQQARA_GIZA_PRINCIPLES"
      value: "true"
      description: "Enable Saqqara-Giza architectural principles"
      ancient_wisdom: true
    
    - name: "DJOSER_IMHOTEP_RELATIONS"
      value: "enabled"
      description: "Activate Djoser-Imhotep client relationship patterns"
      ancient_wisdom: true
    
    - name: "POLYMATH_VIZIER_LOGIC"
      value: "active"
      description: "Enable Polymath Vizier AI logic"
      ancient_wisdom: true
    
    - name: "GOLDEN_RATIO"
      value: "1.618033988749"
      description: "Golden ratio for sacred geometry calculations"
      ancient_wisdom: true

  # Application Ports
  ports:
    - name: "SAQQARA_WORKFLOW_PORT"
      value: "3003"
      description: "Port for Saqqara Workflow Next.js app"
    
    - name: "POLYSTACK_IDE_PORT"
      value: "3002"
      description: "Port for PolyStack IDE Electron app"
    
    - name: "GDATANOMOCS_PORT"
      value: "3001"
      description: "Port for gDaTaNomOcS React Native API"

  # Samsung & Security
  samsung_security:
    - name: "SAMSUNG_ULTRA_EXCLUSIVE"
      value: "true"
      description: "Enable Samsung Ultra exclusive features"
      samsung_exclusive: true
    
    - name: "KNOX_SECURITY_LEVEL"
      value: "MAXIMUM"
      description: "Samsung Knox security level"
      samsung_exclusive: true
    
    - name: "DATA_SOVEREIGNTY_MODE"
      value: "NATIVE_BLOCKING"
      description: "Data sovereignty protection mode"

  # LiquiNomOcs Economics
  liquidnomocs:
    - name: "LAND_BASE_MULTIPLIER"
      value: "1.2"
      description: "Land resource base multiplier"
      ancient_wisdom: true
    
    - name: "AIR_BASE_MULTIPLIER"
      value: "0.8"
      description: "Air resource base multiplier"
      ancient_wisdom: true
    
    - name: "WATER_BASE_MULTIPLIER"
      value: "1.5"
      description: "Water resource base multiplier"
      ancient_wisdom: true
    
    - name: "ANTI_COLONIAL_RESISTANCE"
      value: "true"
      description: "Enable anti-colonial economic resistance tools"
      ancient_wisdom: true

# Automation Rules
automation:
  # Auto-create secrets from templates
  secret_templates:
    - pattern: "*_API_KEY"
      generate: "uuid_v4"
      prefix: "gtek_"
    
    - pattern: "*_PASSWORD"
      generate: "secure_random_32"
      charset: "alphanumeric_symbols"
    
    - pattern: "*_TOKEN"
      generate: "jwt_style"
      issuer: "gtek-ecosystem"

  # Validation Rules
  validation:
    - rule: "iron_rule_compliant"
      check: "no_employment_terms"
      terms: ["hire", "employment", "salary", "wage"]
    
    - rule: "ancient_wisdom"
      check: "saqqara_giza_alignment"
      required_fields: ["codex_sovereign_id", "rhodium_backing"]
    
    - rule: "samsung_exclusive"
      check: "knox_integration"
      required_secrets: ["KNOX_API_KEY", "SAMSUNG_DEV_KEY"]

  # Environment Sync
  sync_rules:
    development:
      copy_from: "variables"
      exclude: ["*_PROD_*", "*_PRODUCTION_*"]
    
    staging:
      copy_from: "secrets"
      include: ["*_STAGING_*", "*_TEST_*"]
      iron_rule_compliant: true
    
    production:
      copy_from: "secrets"
      include: ["*_PROD_*", "*_PRODUCTION_*"]
      require_rhodium_verification: true

# Compliance & Audit
compliance:
  iron_rule_framework:
    - check: "commission_only_structure"
      frequency: "on_push"
      remediation: "auto_fix"
    
    - check: "rhodium_collateralization"
      frequency: "daily"
      threshold: "15_percent"
    
    - check: "ancient_wisdom_integration"
      frequency: "weekly"
      saqqara_giza_score: "minimum_80"

  security:
    - check: "secret_rotation"
      frequency: "monthly"
      exclude: ["CODEX_SOVEREIGN_ID"]
    
    - check: "knox_attestation"
      frequency: "daily"
      samsung_exclusive: true
    
    - check: "data_sovereignty"
      frequency: "continuous"
      native_blocking: true

# Notification Settings
notifications:
  channels:
    - type: "slack"
      webhook_secret: "SLACK_WEBHOOK_URL"
      events: ["secret_created", "secret_updated", "compliance_violation"]
    
    - type: "email"
      recipients: ["jerome@homemadeproductions.com"]
      events: ["iron_rule_violation", "rhodium_threshold_breach"]
    
    - type: "github_issue"
      labels: ["iron-rule", "ancient-wisdom", "security"]
      events: ["compliance_failure", "security_audit_failure"]

  templates:
    iron_rule_violation:
      title: "⚖️ Iron Rule Framework Violation Detected"
      body: |
        Ancient wisdom protocols have detected a violation of the Iron Rule Framework.
        
        **Violation Type**: {violation_type}
        **Details**: {violation_details}
        **Remediation**: {suggested_fix}
        
        Codex Sovereign ID: DIV-LA-JHILL-STFL02035
        Commission-only structure must be maintained.
    
    rhodium_threshold:
      title: "💎 Rhodium Collateralization Below Threshold"
      body: |
        Rhodium backing has fallen below the required 15% threshold.
        
        **Current Level**: {current_percentage}%
        **Required Level**: 15%
        **Action Required**: Add rhodium collateral or reduce scope
        
        Ancient wisdom demands proper collateralization.